In [2]:
import numpy as np

In [3]:
np.__version__

'1.26.4'

In [4]:
np.__doc__

'\nNumPy\n=====\n\nProvides\n  1. An array object of arbitrary homogeneous items\n  2. Fast mathematical operations over arrays\n  3. Linear Algebra, Fourier Transforms, Random Number Generation\n\nHow to use the documentation\n----------------------------\nDocumentation is available in two forms: docstrings provided\nwith the code, and a loose standing reference guide, available from\n`the NumPy homepage <https://numpy.org>`_.\n\nWe recommend exploring the docstrings using\n`IPython <https://ipython.org>`_, an advanced Python shell with\nTAB-completion and introspection capabilities.  See below for further\ninstructions.\n\nThe docstring examples assume that `numpy` has been imported as ``np``::\n\n  >>> import numpy as np\n\nCode snippets are indicated by three greater-than signs::\n\n  >>> x = 42\n  >>> x = x + 1\n\nUse the built-in ``help`` function to view a function\'s docstring::\n\n  >>> help(np.sort)\n  ... # doctest: +SKIP\n\nFor some objects, ``np.info(obj)`` may provide add

In [5]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [6]:
l=[1,2,3,4,5,6]
np.array(l)

array([1, 2, 3, 4, 5, 6])

In [7]:
l.append(3.4)
print(l)
np.array(l)

[1, 2, 3, 4, 5, 6, 3.4]


array([1. , 2. , 3. , 4. , 5. , 6. , 3.4])

In [8]:
l.append("Ram")
print(l)
np.array(l)

[1, 2, 3, 4, 5, 6, 3.4, 'Ram']


array(['1', '2', '3', '4', '5', '6', '3.4', 'Ram'], dtype='<U32')

In [9]:
t=(12,3,4,4,5,67,8,)
np.array(t)

array([12,  3,  4,  4,  5, 67,  8])

In [10]:
t=(1,2,3,4,5,5,6,"Ram")

In [11]:
np.asarray(t)

array(['1', '2', '3', '4', '5', '5', '6', 'Ram'], dtype='<U11')

In [12]:
np.matrix(l)

matrix([['1', '2', '3', '4', '5', '6', '3.4', 'Ram']], dtype='<U32')

In [13]:
mat= np.matrix([[1,2,3],[4,5,6]])

In [14]:
mat

matrix([[1, 2, 3],
        [4, 5, 6]])

In [15]:
np.array(mat)

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
np.asarray(mat)

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
np.asanyarray(mat) # it convert those into array who are not already array or subclass of array 

matrix([[1, 2, 3],
        [4, 5, 6]])

In [18]:
arr= np.array([ i for i in range(5)])

In [19]:
arr

array([0, 1, 2, 3, 4])

In [20]:
arr[0]

0

In [21]:
arr[4]

4

In [22]:
arr[8] #IndexError:outofBound

IndexError: index 8 is out of bounds for axis 0 with size 5

In [ ]:
arr[4]

4

In [ ]:
a=arr #shallow copy
a

array([0, 1, 2, 3, 4])

In [ ]:
arr[0]=100

In [ ]:
arr

array([100,   1,   2,   3,   4])

In [ ]:
a

array([100,   1,   2,   3,   4])

In [ ]:
arr=np.array([i for i in range(1,14,2)])

In [ ]:
arr

array([ 1,  3,  5,  7,  9, 11, 13])

In [ ]:
a=arr.copy() #deep copy

In [ ]:
arr[6]=1999

In [ ]:
arr

array([   1,    3,    5,    7,    9,   11, 1999])

In [ ]:
a

array([ 1,  3,  5,  7,  9, 11, 13])

In [ ]:
np.fromfunction(lambda i:i**2 ,shape=(7,))

array([ 0.,  1.,  4.,  9., 16., 25., 36.])

In [ ]:
arr=np.fromfunction(lambda i,j:i-j,(4,7) )

In [ ]:
arr

array([[ 0., -1., -2., -3., -4., -5., -6.],
       [ 1.,  0., -1., -2., -3., -4., -5.],
       [ 2.,  1.,  0., -1., -2., -3., -4.],
       [ 3.,  2.,  1.,  0., -1., -2., -3.]])

In [ ]:
arr=np.fromfunction(lambda i,j: i==j,(5,5))

In [ ]:
arr

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True]])

In [ ]:
arr=np.fromfunction(lambda i,j,k: i+j*k , (4,4,4))

In [ ]:
arr

array([[[ 0.,  0.,  0.,  0.],
        [ 0.,  1.,  2.,  3.],
        [ 0.,  2.,  4.,  6.],
        [ 0.,  3.,  6.,  9.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  2.,  3.,  4.],
        [ 1.,  3.,  5.,  7.],
        [ 1.,  4.,  7., 10.]],

       [[ 2.,  2.,  2.,  2.],
        [ 2.,  3.,  4.,  5.],
        [ 2.,  4.,  6.,  8.],
        [ 2.,  5.,  8., 11.]],

       [[ 3.,  3.,  3.,  3.],
        [ 3.,  4.,  5.,  6.],
        [ 3.,  5.,  7.,  9.],
        [ 3.,  6.,  9., 12.]]])

In [ ]:
arr.ndim

3

In [ ]:
arr=np.fromfunction(lambda i:i,(4,))

In [ ]:
arr

array([[0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.]])

In [ ]:
np.fromfunction(lambda i,j: i*j , (4,5) ,dtype=int)

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12]])

In [ ]:
l=[i for i in range(4,100,5)]

In [ ]:
type(l)

list

In [ ]:
l

[4, 9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59, 64, 69, 74, 79, 84, 89, 94, 99]

In [ ]:
np.fromiter(l, dtype=int)

array([ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59, 64, 69, 74, 79, 84,
       89, 94, 99])

In [ ]:
t= tuple((i for i in range(10,100,5)))

(10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95)

In [ ]:
iter(t)


In [ ]:
arr=np.fromiter(t, dtype=float)

In [ ]:
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr.ndim

1

In [ ]:
np.fromstring("22 34 65 65 34 342 12", sep=" ", dtype=int)

array([ 22,  34,  65,  65,  34, 342,  12])

In [ ]:
str="Ram,Shyam,Ghanshyam,Mohan,Krishna"
np.fromstring(str, sep=",")  # formstring fun only work with numeric type value 

C:\Users\msi\AppData\Local\Temp\ipykernel_17768\2032160372.py:2: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring(str, sep=",")  # formstring fun only work with numeric type value


array([], dtype=float64)

In [ ]:
str

'Ram,Shyam,Ghanshyam,Mohan,Krishna'

In [ ]:
l=str.split(",")

In [ ]:
l

['Ram', 'Shyam', 'Ghanshyam', 'Mohan', 'Krishna']

In [ ]:
np.asanyarray(l)

array(['Ram', 'Shyam', 'Ghanshyam', 'Mohan', 'Krishna'], dtype='<U9')

In [ ]:
arr=np.arange(0,50,5)

In [ ]:
arr

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
arr=np.linspace(1,500,20)

In [ ]:
arr

array([  1.        ,  27.26315789,  53.52631579,  79.78947368,
       106.05263158, 132.31578947, 158.57894737, 184.84210526,
       211.10526316, 237.36842105, 263.63157895, 289.89473684,
       316.15789474, 342.42105263, 368.68421053, 394.94736842,
       421.21052632, 447.47368421, 473.73684211, 500.        ])

In [ ]:
np.linspace(0,1,30)

array([0.        , 0.03448276, 0.06896552, 0.10344828, 0.13793103,
       0.17241379, 0.20689655, 0.24137931, 0.27586207, 0.31034483,
       0.34482759, 0.37931034, 0.4137931 , 0.44827586, 0.48275862,
       0.51724138, 0.55172414, 0.5862069 , 0.62068966, 0.65517241,
       0.68965517, 0.72413793, 0.75862069, 0.79310345, 0.82758621,
       0.86206897, 0.89655172, 0.93103448, 0.96551724, 1.        ])

In [ ]:
np.logspace(1,30,4)

array([1.00000000e+01, 4.64158883e+10, 2.15443469e+20, 1.00000000e+30])

In [ ]:
np.logspace(4,5,100,base=2)

array([16.        , 16.11241687, 16.22562359, 16.3396257 , 16.4544288 ,
       16.57003851, 16.6864605 , 16.80370048, 16.9217642 , 17.04065743,
       17.16038602, 17.28095582, 17.40237276, 17.52464278, 17.64777187,
       17.77176607, 17.89663147, 18.02237417, 18.14900036, 18.27651622,
       18.40492802, 18.53424204, 18.66446463, 18.79560218, 18.9276611 ,
       19.06064788, 19.19456902, 19.32943111, 19.46524074, 19.60200458,
       19.73972933, 19.87842175, 20.01808862, 20.1587368 , 20.30037318,
       20.44300471, 20.58663837, 20.73128121, 20.87694032, 21.02362284,
       21.17133595, 21.32008691, 21.469883  , 21.62073157, 21.77264   ,
       21.92561576, 22.07966632, 22.23479926, 22.39102217, 22.54834271,
       22.70676859, 22.86630758, 23.0269675 , 23.18875623, 23.35168169,
       23.51575188, 23.68097483, 23.84735864, 24.01491148, 24.18364156,
       24.35355714, 24.52466656, 24.6969782 , 24.87050051, 25.045242  ,
       25.22121123, 25.39841683, 25.57686749, 25.75657195, 25.93

In [ ]:
import numpy as np


In [ ]:
arr=np.zeros((3,4))

In [ ]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.zeros((4,5), dtype= int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.ones(shape=(3,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
np.zeros((4), dtype=float)

array([0., 0., 0., 0.])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.eye(4,dtype= int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [ ]:
np.empty(shape=(4,5), dtype=int)

array([[-1, -1,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0]])

In [ ]:
np.empty((2,2,3), dtype=int)

array([[[4128860, 6029375, 3801155],
        [5570652, 6619251, 7536754]],

       [[7143516, 6881395,       0],
        [      0,   65793,  917504]]])

In [ ]:
import random
random.choice("Saurabh")

'r'

In [ ]:
random.choice([1,2,3,4,5,4,3,2])

3

In [ ]:
random.randrange(200,300)

206

In [ ]:
random.randint(3,7)

4

In [ ]:
random.random()

0.6024786284910029

In [ ]:
l=[i for i in range(8)]
l

[0, 1, 2, 3, 4, 5, 6, 7]

In [ ]:
random.shuffle(l)
l

[7, 1, 4, 3, 2, 0, 5, 6]

In [ ]:
np.random.random_sample()

0.8214232826313018

In [ ]:
np.random.random_sample(size=3)

array([0.88825508, 0.96718586, 0.0400321 ])

In [ ]:
np.random.random_sample((4,5))

array([[0.6769115 , 0.81428113, 0.31286889, 0.35656419, 0.71627794],
       [0.23599471, 0.39038134, 0.78912334, 0.04812584, 0.55914113],
       [0.25573087, 0.76326776, 0.7710344 , 0.77684706, 0.36651266],
       [0.35044235, 0.70289765, 0.89950743, 0.96299203, 0.34973439]])

In [ ]:
np.random.rand()

0.9463992918694816

In [ ]:
np.random.rand(3)

array([0.60462546, 0.78913932, 0.41031042])

In [ ]:
np.random.rand(3,5)

array([[0.92477922, 0.9599915 , 0.94629967, 0.16868679, 0.27614399],
       [0.5276848 , 0.12146932, 0.18988578, 0.48724031, 0.925659  ],
       [0.93216197, 0.9272824 , 0.39495415, 0.47901232, 0.92559796]])

In [ ]:
np.random.randn(4,3)

array([[ 1.51900785,  0.51364158, -0.47680683],
       [-1.65576858,  0.98668212, -0.48814734],
       [-1.38001151,  1.70542896, -1.01300443],
       [-0.51336055,  1.89999313, -0.33981983]])

In [ ]:
arr1=np.random.randint(1,4 ,(4,5) )

In [ ]:
arr1

array([[1, 1, 3, 2, 2],
       [1, 2, 2, 2, 2],
       [2, 2, 2, 1, 1],
       [3, 3, 1, 2, 3]])

In [ ]:
arr1.reshape((10,2))

array([[1, 1],
       [3, 2],
       [2, 1],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 1],
       [1, 3],
       [3, 1],
       [2, 3]])

In [ ]:
arr1

array([[1, 1, 3, 2, 2],
       [1, 2, 2, 2, 2],
       [2, 2, 2, 1, 1],
       [3, 3, 1, 2, 3]])

In [ ]:
arr1.reshape((20,-1))

array([[1],
       [1],
       [3],
       [2],
       [2],
       [1],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [1],
       [1],
       [3],
       [3],
       [1],
       [2],
       [3]])

In [ ]:
arr1.reshape(-1, 2)

array([[1, 1],
       [3, 2],
       [2, 1],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 1],
       [1, 3],
       [3, 1],
       [2, 3]])

In [ ]:
arr1


array([[1, 1, 3, 2, 2],
       [1, 2, 2, 2, 2],
       [2, 2, 2, 1, 1],
       [3, 3, 1, 2, 3]])

In [ ]:
arr1.reshape(5,-1).base

array([[1, 1, 3, 2, 2],
       [1, 2, 2, 2, 2],
       [2, 2, 2, 1, 1],
       [3, 3, 1, 2, 3]])

In [ ]:
arr= np.random.randint(1,20, size=(5,5))

In [ ]:
arr

array([[ 5, 18, 12,  9,  7],
       [16,  9, 12, 18, 13],
       [13,  4,  2, 11,  7],
       [ 8, 12, 11, 14, 19],
       [10, 10,  2,  3,  2]])

In [ ]:
arr>3

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True, False, False, False]])

In [ ]:
arr[arr>4]

array([ 5, 18, 12,  9,  7, 16,  9, 12, 18, 13, 13, 11,  7,  8, 12, 11, 14,
       19, 10, 10])

In [ ]:
arr[arr==4]

array([4])

In [ ]:
arr*100

array([[ 500, 1800, 1200,  900,  700],
       [1600,  900, 1200, 1800, 1300],
       [1300,  400,  200, 1100,  700],
       [ 800, 1200, 1100, 1400, 1900],
       [1000, 1000,  200,  300,  200]])

In [ ]:
arr/50


array([[0.1 , 0.36, 0.24, 0.18, 0.14],
       [0.32, 0.18, 0.24, 0.36, 0.26],
       [0.26, 0.08, 0.04, 0.22, 0.14],
       [0.16, 0.24, 0.22, 0.28, 0.38],
       [0.2 , 0.2 , 0.04, 0.06, 0.04]])

In [ ]:
arr*200

array([[1000, 3600, 2400, 1800, 1400],
       [3200, 1800, 2400, 3600, 2600],
       [2600,  800,  400, 2200, 1400],
       [1600, 2400, 2200, 2800, 3800],
       [2000, 2000,  400,  600,  400]])

In [ ]:
arr

array([[ 5, 18, 12,  9,  7],
       [16,  9, 12, 18, 13],
       [13,  4,  2, 11,  7],
       [ 8, 12, 11, 14, 19],
       [10, 10,  2,  3,  2]])

In [ ]:
arr[0]

array([ 5, 18, 12,  9,  7])

In [ ]:
arr[0:4]

array([[ 5, 18, 12,  9,  7],
       [16,  9, 12, 18, 13],
       [13,  4,  2, 11,  7],
       [ 8, 12, 11, 14, 19]])

In [ ]:
arr[1:3, [1,4]]

array([[ 9, 13],
       [ 4,  7]])

In [ ]:
arr[0:4,1:4]

array([[18, 12,  9],
       [ 9, 12, 18],
       [ 4,  2, 11],
       [12, 11, 14]])

Matrix multiplication

In [ ]:
arr1= np.random.randint(1,40, size=(4,4))
arr2= np.random.randint(4,50, size=(4,6))

In [ ]:
arr1

array([[14, 19, 35, 11],
       [14, 27, 25, 14],
       [31,  6, 20,  3],
       [35, 28, 12,  2]])

In [ ]:
arr2

array([[12, 19, 17, 40, 20, 38],
       [15, 17, 37, 14, 20, 30],
       [ 7, 12, 44, 16, 15,  5],
       [36, 18, 14, 16, 18, 29]])

In [ ]:
arr1@ arr2

array([[1094, 1207, 2635, 1562, 1383, 1596],
       [1252, 1277, 2533, 1562, 1447, 1873],
       [ 710,  985, 1671, 1692, 1094, 1545],
       [ 996, 1321, 2187, 2016, 1476, 2288]])

In [ ]:
np.dot(arr1,arr2)

array([[1094, 1207, 2635, 1562, 1383, 1596],
       [1252, 1277, 2533, 1562, 1447, 1873],
       [ 710,  985, 1671, 1692, 1094, 1545],
       [ 996, 1321, 2187, 2016, 1476, 2288]])

In [23]:
arr1=np.zeros(shape=(4,4) , dtype=int)

In [24]:
arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
a=np.array([i for i in  range(6)])

In [ ]:
a

array([0, 1, 2, 3, 4, 5])

In [ ]:
arr=arr1+a[0:4]

In [ ]:
arr

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [ ]:
arr=arr.T
arr

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [ ]:
np.sqrt(arr)

array([[0.        , 0.        , 0.        , 0.        ],
       [1.        , 1.        , 1.        , 1.        ],
       [1.41421356, 1.41421356, 1.41421356, 1.41421356],
       [1.73205081, 1.73205081, 1.73205081, 1.73205081]])

In [ ]:
arr=np.ones((4,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.log10(arr)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr+6

array([[7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.]])

In [25]:
arr=np.exp(arr1)

arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
np.max(arr1)

0

In [28]:
np.min(arr)

1.0

In [30]:
arr=np.random.randn(4,5)

In [31]:
arr

array([[-0.21427501, -0.91230047, -0.24525776, -0.60739533, -0.82454723],
       [-2.03869187, -1.00326307,  0.67901939, -1.28397109,  0.79483557],
       [-0.06228488,  0.31675862,  0.77496806, -0.92806959, -0.83043742],
       [-0.73550866,  0.11525771, -0.05830837, -1.68367453, -1.00326987]])

In [32]:
arr.flatten()

array([-0.21427501, -0.91230047, -0.24525776, -0.60739533, -0.82454723,
       -2.03869187, -1.00326307,  0.67901939, -1.28397109,  0.79483557,
       -0.06228488,  0.31675862,  0.77496806, -0.92806959, -0.83043742,
       -0.73550866,  0.11525771, -0.05830837, -1.68367453, -1.00326987])

In [36]:
arr=np.random.rand(2,4,5)

In [37]:
arr

array([[[0.2220182 , 0.17174321, 0.0019648 , 0.34541169, 0.81316209],
        [0.92009881, 0.52901331, 0.54559396, 0.64812075, 0.74355243],
        [0.03168329, 0.66137431, 0.14752706, 0.03907109, 0.49051465],
        [0.17620463, 0.8012977 , 0.6283182 , 0.97195248, 0.02372716]],

       [[0.11296915, 0.01078489, 0.67702719, 0.41852182, 0.10008436],
        [0.14399425, 0.35430694, 0.00163118, 0.44768534, 0.74283766],
        [0.42409625, 0.59021542, 0.02044151, 0.13192516, 0.75749971],
        [0.16737984, 0.91082703, 0.07021069, 0.10273753, 0.88976099]]])

In [38]:
arr.flatten()

array([0.2220182 , 0.17174321, 0.0019648 , 0.34541169, 0.81316209,
       0.92009881, 0.52901331, 0.54559396, 0.64812075, 0.74355243,
       0.03168329, 0.66137431, 0.14752706, 0.03907109, 0.49051465,
       0.17620463, 0.8012977 , 0.6283182 , 0.97195248, 0.02372716,
       0.11296915, 0.01078489, 0.67702719, 0.41852182, 0.10008436,
       0.14399425, 0.35430694, 0.00163118, 0.44768534, 0.74283766,
       0.42409625, 0.59021542, 0.02044151, 0.13192516, 0.75749971,
       0.16737984, 0.91082703, 0.07021069, 0.10273753, 0.88976099])

In [40]:
arr=np.random.randint(1,9,5)

In [44]:
arr


array([4, 2, 2, 5, 3])

In [46]:
np.expand_dims(arr, axis=0)

array([[4, 2, 2, 5, 3]])

In [48]:
np.expand_dims(arr, axis=1)

array([[4],
       [2],
       [2],
       [5],
       [3]])

In [50]:
arr=np.random.randint(3,20,(3,4))

In [51]:
arr

array([[18,  6,  6,  4],
       [12,  7, 17, 12],
       [17, 18,  5, 16]])

In [52]:
np.expand_dims(arr, axis=0)

array([[[18,  6,  6,  4],
        [12,  7, 17, 12],
        [17, 18,  5, 16]]])

In [55]:
arr=np.expand_dims(arr, axis=1)
arr

array([[[[18,  6,  6,  4]]],


       [[[12,  7, 17, 12]]],


       [[[17, 18,  5, 16]]]])

In [58]:
arr=arr.squeeze()
arr

array([[18,  6,  6,  4],
       [12,  7, 17, 12],
       [17, 18,  5, 16]])

In [82]:
arr=np.random.randint(3,20,(1,1,10))

In [85]:
arr

array([[[ 8, 18,  9,  3, 12, 12, 15,  7,  7, 12]]])

In [86]:
arr.squeeze()

array([ 8, 18,  9,  3, 12, 12, 15,  7,  7, 12])

In [87]:
arr

array([[[ 8, 18,  9,  3, 12, 12, 15,  7,  7, 12]]])

In [88]:
np.repeat(arr,4)

array([ 8,  8,  8,  8, 18, 18, 18, 18,  9,  9,  9,  9,  3,  3,  3,  3, 12,
       12, 12, 12, 12, 12, 12, 12, 15, 15, 15, 15,  7,  7,  7,  7,  7,  7,
        7,  7, 12, 12, 12, 12])

In [110]:
arr1=np.random.randint(1,20,(5,5))

In [111]:
arr1


array([[12,  8, 18,  1,  6],
       [11, 12, 10, 11,  4],
       [16, 14,  6,  4, 13],
       [14, 11,  5, 14, 14],
       [10, 17,  9,  8, 19]])

In [113]:
np.roll(arr1,3,axis=0)

array([[16, 14,  6,  4, 13],
       [14, 11,  5, 14, 14],
       [10, 17,  9,  8, 19],
       [12,  8, 18,  1,  6],
       [11, 12, 10, 11,  4]])

In [114]:
#operation on string array

In [115]:
arr=np.array(["Ram","Shyam","Ghanshayam","Lakshmana"])

In [116]:
arr

array(['Ram', 'Shyam', 'Ghanshayam', 'Lakshmana'], dtype='<U10')

In [118]:
np.char.upper(arr)

array(['RAM', 'SHYAM', 'GHANSHAYAM', 'LAKSHMANA'], dtype='<U10')

In [119]:
np.char.lower(arr)

array(['ram', 'shyam', 'ghanshayam', 'lakshmana'], dtype='<U10')

In [121]:
np.char.count(arr,"a")

array([1, 1, 3, 3])

In [123]:
np.char.center(arr, width=10)

array(['   Ram    ', '  Shyam   ', 'Ghanshayam', 'Lakshmana '],
      dtype='<U10')

In [124]:
# Linear algebra

In [128]:
arr=np.random.randint(3,30,(4,4))

In [129]:
arr

array([[14,  3, 26, 10],
       [13, 12,  5,  4],
       [12, 28,  9, 13],
       [13,  7, 12, 17]])

In [130]:
np.linalg.det(arr)

59991.99999999991

In [131]:
np.linalg.inv(arr)

array([[-0.01448526,  0.12149953, -0.0562575 ,  0.02295306],
       [ 0.0017669 , -0.01136818,  0.04943993, -0.03617149],
       [ 0.0577577 , -0.04142219,  0.02178624, -0.04088879],
       [-0.03042072, -0.0589912 ,  0.0072843 ,  0.085028  ]])

Linear equation


In [132]:
# 7x + 3y + 8z = 12
# 9x + 3.4y = 23
# 3x + y + 5z = 14.6

In [133]:
arr1=np.array([[7,3,8],[9,3.4,0],[3,1,5]])

In [134]:
arr1

array([[7. , 3. , 8. ],
       [9. , 3.4, 0. ],
       [3. , 1. , 5. ]])

In [135]:
arr2=np.array([12,23,14.6])

In [136]:
arr2

array([12. , 23. , 14.6])

In [137]:
sol=np.linalg.solve(arr1,arr2)

In [138]:
sol

array([ 13.8328125, -29.8515625,   0.590625 ])

In [139]:
arr

array([[14,  3, 26, 10],
       [13, 12,  5,  4],
       [12, 28,  9, 13],
       [13,  7, 12, 17]])

In [140]:
np.sqrt(arr)

array([[3.74165739, 1.73205081, 5.09901951, 3.16227766],
       [3.60555128, 3.46410162, 2.23606798, 2.        ],
       [3.46410162, 5.29150262, 3.        , 3.60555128],
       [3.60555128, 2.64575131, 3.46410162, 4.12310563]])

In [141]:
np.log10(arr)

array([[1.14612804, 0.47712125, 1.41497335, 1.        ],
       [1.11394335, 1.07918125, 0.69897   , 0.60205999],
       [1.07918125, 1.44715803, 0.95424251, 1.11394335],
       [1.11394335, 0.84509804, 1.07918125, 1.23044892]])

In [142]:
np.exp(arr)

array([[1.20260428e+06, 2.00855369e+01, 1.95729609e+11, 2.20264658e+04],
       [4.42413392e+05, 1.62754791e+05, 1.48413159e+02, 5.45981500e+01],
       [1.62754791e+05, 1.44625706e+12, 8.10308393e+03, 4.42413392e+05],
       [4.42413392e+05, 1.09663316e+03, 1.62754791e+05, 2.41549528e+07]])

In [143]:
np.min(arr)

3

In [144]:
np.max(arr)

28

In [145]:
np.sin(arr)

array([[ 0.99060736,  0.14112001,  0.76255845, -0.54402111],
       [ 0.42016704, -0.53657292, -0.95892427, -0.7568025 ],
       [-0.53657292,  0.27090579,  0.41211849,  0.42016704],
       [ 0.42016704,  0.6569866 , -0.53657292, -0.96139749]])

In [146]:
np.cos(arr)

array([[ 0.13673722, -0.9899925 ,  0.64691932, -0.83907153],
       [ 0.90744678,  0.84385396,  0.28366219, -0.65364362],
       [ 0.84385396, -0.96260587, -0.91113026,  0.90744678],
       [ 0.90744678,  0.75390225,  0.84385396, -0.27516334]])

In [147]:
np.tan(arr)

array([[ 7.24460662, -0.14254654,  1.17875355,  0.64836083],
       [ 0.46302113, -0.63585993, -3.38051501,  1.15782128],
       [-0.63585993, -0.2814296 , -0.45231566,  0.46302113],
       [ 0.46302113,  0.87144798, -0.63585993,  3.49391565]])

In [148]:
np.power(arr,2)

array([[196,   9, 676, 100],
       [169, 144,  25,  16],
       [144, 784,  81, 169],
       [169,  49, 144, 289]], dtype=int32)

In [149]:
np.mean(arr)

12.375

In [156]:
np.searchsorted([23,54,6],[23,4,5])

array([0, 0, 0], dtype=int64)

In [157]:
np.count_nonzero(arr)

16

In [158]:
np.where(arr>0)

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3], dtype=int64),
 array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))

In [160]:
np.extract(arr>3, arr)

array([14, 26, 10, 13, 12,  5,  4, 12, 28,  9, 13, 13,  7, 12, 17])

In [161]:
arr.byteswap()

array([[234881024,  50331648, 436207616, 167772160],
       [218103808, 201326592,  83886080,  67108864],
       [201326592, 469762048, 150994944, 218103808],
       [218103808, 117440512, 201326592, 285212672]])